CREATE TABLE IF NOT EXISTS Genres(
Id INT PRIMARY KEY AUTO_INCREMENT,
Name NVARCHAR(50)
);


CREATE TABLE IF NOT EXISTS Artists(
Id INT PRIMARY KEY AUTO_INCREMENT,
Name NVARCHAR(50),
Country NVARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Songs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    artistId INT,
    album VARCHAR(255),
    genreId INT,
    releaseYear INT,
    duration DOUBLE
);